# Generated by Django 5.1.4 on 2025-01-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата последнего изменения продукта",
                verbose_name="Дата последнего изменения",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Введите текст статьи",
                null=True,
                verbose_name="Содержание статьи",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата создания продукта",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(
                help_text="Введите название заголовка",
                max_length=200,
                verbose_name="Заголовок",
            ),
        ),
    ]
