# Generated by Django 5.1.4 on 2025-01-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_updated_at_alter_blogpost_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата создания поста",
                verbose_name="Дата создания",
            ),
        ),
    ]
