# Generated by Django 5.1.4 on 2025-02-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
