# Generated by Django 5.1.4 on 2025-01-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фотографию продукта",
                null=True,
                upload_to="category/photo",
                verbose_name="Фотография продукта",
            ),
        ),
    ]
